name: "CI: gocsv package"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master

jobs:
  build-test-scan:
    name: Build, Test & Scan
    runs-on: ubuntu-latest
    env:
      ACTIONS_BUILD_ID: ${{ github.run_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Go Version
        id: set-go-version
        run: |
          go_version=$(awk '/^go/{print $NF}' go.mod)
          [ -z "$go_version" ] && go_version=^1.15
          echo "::set-output name=go_version::$(echo $go_version)"
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.set-go-version.outputs.go_version }}
      
      - name: Build
        run: go build -v ./...

      - name: Test
        run: make test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
